In [14]:
# Column-wise sort indices
# np.set_printoptions(threshold=np.inf)
np.set_printoptions(threshold=np.inf, linewidth=200, suppress=True)

import numpy as np
mat=np.random.randint(0,256,(10,10,3))
# print(mat)
for i in range(mat.shape[0]):
    for j in range(mat.shape[1]):
        mat[i][j][1]=i
        mat[i][j][2]=j
print(mat)

[[[ 40   0   0]
  [243   0   1]
  [ 18   0   2]
  [235   0   3]
  [188   0   4]
  [ 83   0   5]
  [ 33   0   6]
  [116   0   7]
  [232   0   8]
  [201   0   9]]

 [[247   1   0]
  [105   1   1]
  [ 50   1   2]
  [177   1   3]
  [207   1   4]
  [252   1   5]
  [ 19   1   6]
  [ 91   1   7]
  [209   1   8]
  [232   1   9]]

 [[ 35   2   0]
  [234   2   1]
  [226   2   2]
  [254   2   3]
  [219   2   4]
  [ 85   2   5]
  [156   2   6]
  [240   2   7]
  [252   2   8]
  [ 69   2   9]]

 [[119   3   0]
  [ 30   3   1]
  [ 67   3   2]
  [206   3   3]
  [203   3   4]
  [ 62   3   5]
  [ 94   3   6]
  [ 58   3   7]
  [ 64   3   8]
  [169   3   9]]

 [[110   4   0]
  [ 46   4   1]
  [158   4   2]
  [213   4   3]
  [175   4   4]
  [220   4   5]
  [199   4   6]
  [186   4   7]
  [160   4   8]
  [245   4   9]]

 [[ 77   5   0]
  [177   5   1]
  [192   5   2]
  [165   5   3]
  [ 23   5   4]
  [173   5   5]
  [  3   5   6]
  [ 66   5   7]
  [179   5   8]
  [ 70   5   9]]

 [[190   6   0]
  [217   6  

In [18]:
# Get sorting indices from the first channel for each row
sort_idx = np.argsort(mat[:, :, 0], axis=1)
# Row indices for broadcasting
rows = np.arange(mat.shape[0])[:, None]
# Apply sorting so all 3 channels follow the first channel's order
sorted_mat = mat[rows, sort_idx]
print(sorted_mat)


[[[ 18   0   2]
  [ 33   0   6]
  [ 40   0   0]
  [ 83   0   5]
  [116   0   7]
  [188   0   4]
  [201   0   9]
  [232   0   8]
  [235   0   3]
  [243   0   1]]

 [[ 19   1   6]
  [ 50   1   2]
  [ 91   1   7]
  [105   1   1]
  [177   1   3]
  [207   1   4]
  [209   1   8]
  [232   1   9]
  [247   1   0]
  [252   1   5]]

 [[ 35   2   0]
  [ 69   2   9]
  [ 85   2   5]
  [156   2   6]
  [219   2   4]
  [226   2   2]
  [234   2   1]
  [240   2   7]
  [252   2   8]
  [254   2   3]]

 [[ 30   3   1]
  [ 58   3   7]
  [ 62   3   5]
  [ 64   3   8]
  [ 67   3   2]
  [ 94   3   6]
  [119   3   0]
  [169   3   9]
  [203   3   4]
  [206   3   3]]

 [[ 46   4   1]
  [110   4   0]
  [158   4   2]
  [160   4   8]
  [175   4   4]
  [186   4   7]
  [199   4   6]
  [213   4   3]
  [220   4   5]
  [245   4   9]]

 [[  3   5   6]
  [ 23   5   4]
  [ 66   5   7]
  [ 70   5   9]
  [ 77   5   0]
  [165   5   3]
  [173   5   5]
  [177   5   1]
  [179   5   8]
  [192   5   2]]

 [[ 49   6   2]
  [101   6  

In [16]:
mat

array([[[ 40,   0,   0],
        [243,   0,   1],
        [ 18,   0,   2],
        [235,   0,   3],
        [188,   0,   4],
        [ 83,   0,   5],
        [ 33,   0,   6],
        [116,   0,   7],
        [232,   0,   8],
        [201,   0,   9]],

       [[247,   1,   0],
        [105,   1,   1],
        [ 50,   1,   2],
        [177,   1,   3],
        [207,   1,   4],
        [252,   1,   5],
        [ 19,   1,   6],
        [ 91,   1,   7],
        [209,   1,   8],
        [232,   1,   9]],

       [[ 35,   2,   0],
        [234,   2,   1],
        [226,   2,   2],
        [254,   2,   3],
        [219,   2,   4],
        [ 85,   2,   5],
        [156,   2,   6],
        [240,   2,   7],
        [252,   2,   8],
        [ 69,   2,   9]],

       [[119,   3,   0],
        [ 30,   3,   1],
        [ 67,   3,   2],
        [206,   3,   3],
        [203,   3,   4],
        [ 62,   3,   5],
        [ 94,   3,   6],
        [ 58,   3,   7],
        [ 64,   3,   8],
        [169,   3, 

In [4]:
# row-wise sort indices
import numpy as np
mat=np.random.randint(0,256,(10,10))
print(mat)
sorted_indices = np.argsort(mat, axis=1)
print(sorted_indices.shape)  # (210, 210)
sorted_indices


[[127 239  94 223 240  34  62  14  41 252]
 [  2 199 248   2  78  13   4 119 127 197]
 [ 40   0  76 101 251 214 129  55 129  42]
 [ 13 203 131 134  36 232  59 138  77  95]
 [ 11  90 138 154 100 112  62 246 237 210]
 [ 88  23  56 165  90 242  34 194 159 234]
 [  7  68 227 196 127 143 123 255  81 224]
 [230 200  38 217 124 107  22 249 161  39]
 [252 175 132 107   8 127 209  24  64 143]
 [229 250 129  27 184 101  24 106 134 132]]
(10, 10)


array([[7, 5, 8, 6, 2, 0, 3, 1, 4, 9],
       [0, 3, 6, 5, 4, 7, 8, 9, 1, 2],
       [1, 0, 9, 7, 2, 3, 6, 8, 5, 4],
       [0, 4, 6, 8, 9, 2, 3, 7, 1, 5],
       [0, 6, 1, 4, 5, 2, 3, 9, 8, 7],
       [1, 6, 2, 0, 4, 8, 3, 7, 9, 5],
       [0, 1, 8, 6, 4, 5, 3, 9, 2, 7],
       [6, 2, 9, 5, 4, 8, 1, 3, 0, 7],
       [4, 7, 8, 3, 5, 2, 9, 1, 6, 0],
       [6, 3, 5, 7, 2, 9, 8, 4, 0, 1]], dtype=int64)